server:
  port: 16379
  servlet:
    context-path: /dynamic-redis

spring:
  profiles:
    active: local

redis-source:
  primary: master
  dynamic:
    master:
      type: node
      host: 127.0.0.1
      port: 6379
      database: 0
      password: ''
      lettuce:
        pool:
          max-active: 8   #最大连接数据库连接数,设 0 为没有限制
          max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
          max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
          min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
        shutdown-timeout: 100ms
    slave:
      type: cluster
      password: '123456'
      timeout: 1000ms
      cluster:
        nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
        max-redirects: 3 #跨集群执行命令时要遵循的最大重定向数量
        max-max-attempts: 2 #重试次数
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        test-on-borrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      lettuce:
        pool:
          max-active: -1 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
          max-idle: 8    # 连接池中的最大空闲连接 ，默认值也是8
          max-wait: -1ms   # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
          min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
        shutdown-timeout: 100ms #默认值也是100ms